Chatyra
Cohort5BankApp/JavaJuvenilesBankApp pull request #17
Opened 2019-06-06 22:49 UTC by cephc

account service and controllers rough draft

2019-06-06 23:13 UTC, Edgetopher commented on src/main/java/com/cohort5/fullbankingapplicationfinal/controller/AccountController.java
> +    @RequestMapping(value = "/customers/{account_id}", method = RequestMethod.GET)
Dont use{account_Id} it will mess with the endpoints, use {accountId}.

2019-06-06 23:14 UTC, Edgetopher requested changes
Check your endpoints. They should match the packet.

2019-06-07 00:56 UTC, brownltaylor commented
also change your account_id variable to a Long instead of a string :)

2019-06-07 01:25 UTC, Edgetopher approved these changes

2019-06-07 01:25 UTC, merged